### ISSUE TITLE
Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by zigazajc007** [Huskehhh/MySQL#18]
When I try to connect into database it give me **Public Key Retrieval is not allowed** error.

I know that I can solve this problem by removing **useSSL = false** or adding option **allowPublicKeyRetrieval=true**, but I can't remove any parameter from pro.husk.mysql.MySQL Object or add any option.

**Comment by Huskehhh** [comment]
Hey man! I just pushed a change to fix this. It can be seen in v1.3.1
https://github.com/Huskehhh/MySQL/blob/master/src/main/java/pro/husk/mysql/MySQL.java#L31

**Comment by zigazajc007** [comment]
Thanks man. You are the best ;)
