### ISSUE TITLE
Can I create a pool of connections?

### ISSUE THREAD

**Issue by TimoA200** [Huskehhh/MySQL#21]
Maybe that's a stupid question, but I'm new to this topic.
I heard that using a pool of MySQL connections is more efficient if you have a lot of requests.
I saw a few examples of pools, which I didn't really understand, so
can I use this wrapper to create a connection pool easily?

**Comment by Huskehhh** [comment]
Hey mate! Certainly no stupid questions.
This wrapper is built on top of [HikariCP](https://github.com/brettwooldridge/HikariCP) which is a popular and incredibly fast connection pool, which does all the pooling for us!
