### ISSUE TITLE
TLS 1.2 disabled maven repo

### ISSUE THREAD

**Issue by A5H73Y** [Huskehhh/MySQL#26]
I'm getting failing building from my Travis builds, 1.8 java.

Failed to execute goal on project Parkour: Could not resolve dependencies for project io.github.a5h73y:Parkour:jar:6.0: Failed to collect dependencies at pro.husk:mysql:jar:1.4.0: Failed to read artifact descriptor for pro.husk:mysql:jar:1.4.0: Could not transfer artifact pro.husk:mysql:pom:1.4.0 from/to husk (https://maven.husk.pro/repository/maven-public/): Received fatal alert: protocol_version -> [Help 1]

**Comment by Huskehhh** [comment]
Hey. Sorry it's been a minute!
Are you still having this issue?

**Comment by Huskehhh** [comment]
Fixed with https://github.com/Huskehhh/MySQL/commit/844c363d59a391d179d8c190241974f5d6814f4f
Note: a repo change will be required
