### ISSUE TITLE
cannot access pro.husk.mysql.MySQL

### ISSUE THREAD

**Issue by hanatic** [Huskehhh/MySQL#29]
When compiling using maven, I get this error:
```
cannot access pro.husk.mysql.MySQL
```

IntelliJ is very unhelpful, I know :(

**Comment by Huskehhh** [comment]
Hi, I'm going to need more information to be able to help.
Please show your pom.xml

**Comment by hanatic** [comment]
Ah, this is awkward. I actually solved it by using a different library. I can try and reproduce it if you want?

**Comment by Huskehhh** [comment]
Hahaha nah mate it's allg! I think I know the problem.
