### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by HugoSilvaF** [Huskehhh/MySQL#30]
when i reload the minecraft server the HikariPool create a new pool connection. However when it arrives at the 20th connection, i get an error. This error:  "Too many connections"
![image](https://user-images.githubusercontent.com/8800040/169220183-719458a5-759a-4292-80a3-58ca67f2da30.png)

My code of start and disable mysql:
```
    private void disableMySQL() {
      try {
         if (mysql != null) {
            mysql.closeConnection();
         }
      } catch (SQLException var2) {
         var2.printStackTrace();
      } 
    }

    private void startMySQL() {
        if (this.getConfig().getBoolean("mysql.enable")) {
           String url = "jdbc:mysql://" + this.getConfig().getString("mysql.host") + ":" + this.getConfig().getString("mysql.port") + "/" + this.getConfig().getString("mysql.database") + "/" + this.getConfig().getString("mysql.username") + "/" + this.getConfig().getString("mysql.password");
           mysql = new MySQL("jdbc:mysql://" + this.getConfig().getString("mysql.host") + ":" + this.getConfig().getString("mysql.port") + "/" + this.getConfig().getString("mysql.database"), this.getConfig().getString("mysql.username"), this.getConfig().getString("mysql.password"));
        }
     }
```
![image](https://user-images.githubusercontent.com/8800040/169219387-8ab677ea-7289-4274-8bc2-33542a9d7138.png)

**Comment by Huskehhh** [comment]
This is not an issue with the library. You need to manage the lifecycle of the connection using the methods available on the server.
